
CREATE DATABASE sitioweb

USE sitioweb

CREATE TABLE USUARIO (
     ID  INT(11) NOT NULL PRIMARY KEY UNIQUE,
     FECHA_REGISTRO DATETIME,
     NOMBRE VARCHAR(100) NOT NULL,
     TELEFONO INT NOT NULL UNIQUE,
     CORREO_ELECTRONICO VARCHAR (50) NOT NULL,
     CONTRASEÑA VARCHAR (50) NOT NULL
)

   
    
